### REGISTRATION
POST http://localhost:9999/api/v1/user/auth/registration
Content-Type: application/json
Accept-Language: uz

{
  "username": "222211m@jdu.uz",
  "name": "Student Muhammadsolih",
  "password": "secret",
  "role": "STUDENT"
}

### REGISTRATION CONFIRM
POST http://localhost:9999/api/v1/user/auth/registration/confirm
Content-Type: application/json
Accept-Language: uz

{
  "username": "222211m@jdu.uz",
  "code": "16062"
}

### RESET PASSWORD
POST http://localhost:9999/api/v1/user/auth/reset-password
Content-Type: application/json
Accept-Language: uz

{
  "username": "222211m@jdu.uz"
}

### RESET PASSWORD CONFIRM
POST http://localhost:9999/api/v1/user/auth/reset-password/confirm
Content-Type: application/json
Accept-Language: uz

{
  "username": "222211m@jdu.uz",
  "code": "67117",
  "newPassword": "secret1234"
}

### LOGIN as STUDENT
POST http://localhost:9999/api/v1/user/auth/login
Content-Type: application/json
Accept-Language: en

{
  "username": "222211m@jdu.uz",
  "password": "secret1234"
}

### LOGIN as TEACHER
POST http://localhost:9999/api/v1/user/auth/login
Content-Type: application/json
Accept-Language: en

{
  "username": "muhammadsolihdesigner@gmail.com",
  "password": "secret"
}

### USER GET ME as TEACHER
GET http://localhost:9999/api/v1/user/me
Content-Type: application/json
Accept-Language: en
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnb2Z1cm92bXVoYW1tYWRzb2xpaDAwNEBnbWFpbC5jb20iLCJpZCI6ImIzM2Q5MjdjLTRjY2MtNDc0Yi04ZDY5LTY5YzMyZDRkNWU5MCIsInJvbGUiOiJURUFDSEVSIiwiaWF0IjoxNzU0NjUyMTc3LCJleHAiOjE3NTQ3Mzg1Nzd9.yuFHoPV-BST62jxCyE_-GUGGCn-GGzomSpKUQtKJX6c

### USER GET ME as STUDENT
GET http://localhost:9999/api/v1/user/me
Content-Type: application/json
Accept-Language: en
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyMjIyMTFtQGpkdS51eiIsImlkIjoiYjZiNzc0NDQtNzQ2Mi00MjdmLThlMGQtN2M0NjAwZDYyZWI5Iiwicm9sZSI6IlNUVURFTlQiLCJpYXQiOjE3NTQ2NDYwMTksImV4cCI6MTc1NDczMjQxOX0.6a56_0Qw_PazbGp5GSKDtavlTFB-2D_kvgePJotVGew
