### UPDATE USERNAME
POST http://localhost:9999/api/v1/user/update/username
Content-Type: application/json
Accept-Language: en
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnb2Z1cm92bXVoYW1tYWRzb2xpaDAwNEBnbWFpbC5jb20iLCJpZCI6ImIzM2Q5MjdjLTRjY2MtNDc0Yi04ZDY5LTY5YzMyZDRkNWU5MCIsInJvbGUiOiJURUFDSEVSIiwiaWF0IjoxNzU0NjUyMTc3LCJleHAiOjE3NTQ3Mzg1Nzd9.yuFHoPV-BST62jxCyE_-GUGGCn-GGzomSpKUQtKJX6c

{
  "newUsername": "gofurovmuhammadsolih004@gmail.com"
}

### UPDATE USERNAME CONFIRM
POST http://localhost:9999/api/v1/user/update/username/confirm
Content-Type: application/json
Accept-Language: en
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJnb2Z1cm92bXVoYW1tYWRzb2xpaDAwNEBnbWFpbC5jb20iLCJpZCI6ImIzM2Q5MjdjLTRjY2MtNDc0Yi04ZDY5LTY5YzMyZDRkNWU5MCIsInJvbGUiOiJURUFDSEVSIiwiaWF0IjoxNzU0NjUyMTc3LCJleHAiOjE3NTQ3Mzg1Nzd9.yuFHoPV-BST62jxCyE_-GUGGCn-GGzomSpKUQtKJX6c

{
  "newUsername": "gofurovmuhammadsolih004@gmail.com",
  "code": "25389"
}
